#OBJS
OBJS = 06_extension_libraries_and_loading_other_image_formats.cpp

#CC
CC = g++

#COMPILER_FLAGS
COMPILER_FLAGS = -Wall

#LINKER_FLAGS
LINKER_FLAGS = -lSDL2 -lSDL2_image

#OBJ_NAME
OBJ_NAME = 06_extension_libraries_and_loading_other_image_formats

#Target
all	:	$(OBJS)
			$(CC)	$(OBJS) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o $(OBJ_NAME)
