#OBJS
OBJS = 02_getting_an_image_on_the_screen.cpp

#CC
CC = g++

#COMPILER_FLAGS
COMPILER_FLAGS = -w

#LINKER_FLAGS
LINKER_FLAGS = -lSDL2

#OBJ_NAME
OBJ_NAME = 02_getting_an_image_on_the_screen

#Target
all	:	$(OBJS)
			$(CC)	$(OBJS) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o $(OBJ_NAME)
