#OBJS
OBJS = 05_optimized_surface_loading_and_soft_stretching.cpp

#CC
CC = g++

#COMPILER_FLAGS
COMPILER_FLAGS = -w

#LINKER_FLAGS
LINKER_FLAGS = -lSDL2

#OBJ_NAME
OBJ_NAME = 05_optimized_surface_loading_and_soft_stretching

#Target
all	:	$(OBJS)
			$(CC)	$(OBJS) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o $(OBJ_NAME)
